title: SYB's Homepage
page-top-title: Welcome to SYB's Homepage
top-section-bg-text: The highest wisdom is to have no fear
home-subtitle: SYB&ensp;|&ensp;Mooncake
copyright-text: '&copy; SYB 2023-2025. All Rights Reserved.'
