title: SYB's Homepage
page-top-title: SYB AKA Mooncake
top-section-bg-text: A heart like still water is invincible.
home-subtitle: SYB&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; SYB 2023-2025. All Rights Reserved.'
